(add-to-list 'load-path "~/.emacs.d/vendor")

(load "amce/theme")
(load "amce/global")
(load "amce/defuns")
(load "amce/disabled")
(load "amce/fonts")
(load "amce/cua")
(load "amce/html")
(load "amce/shell")
(load "amce/package")
(load "amce/ido")
(load "amce/guide-key")

(vendor 'golden-ratio)
(vendor 'markdown-mode)
(load "amce/golden-ratio")
(load "amce/markdown-mode")
