(setq custom-file "~/.emacs.d/custom-settings.el")
(load custom-file)
(load-file "~/.emacs.d/funs.el")
(load-file "~/.emacs.d/global.el")
(load-file "~/.emacs.d/modes.el")
(load-file  "~/.emacs.d/packages.el")
